url: https://y7kim.github.io
baseurl: 
# Site settings
title: Kat Heiden | Writer & Storyteller
email: kat.heiden22@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Kat Heiden
  pic: 1
  position: Writer - Storyteller
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/imagine_kat
  - title: facebook
    url: https://www.facebook.com/kat.heiden
  - title: linkedin
    url: https://www.linkedin.com/in/katheiden22/
# Postal address (add as many lines as necessary)
address:
  - line: 10890 Vrain St.
  - line: Westminster, CO 80031

# Build settings
markdown: kramdown
permalink: pretty