url: https://cjheiden227.github.io/agency-jekyll-theme/
baseurl: 
# Site settings
title: Kat Heiden | Writer & Storyteller
email: kat.heiden22@gmail.com
description: "Storytelling is the way we’ve communicated with each other for millennia, and it works. That’s why storytelling is the basis of everything I do."


# Team names, titles and social links
people:
- name: Kat Heiden
  pic: 1
  position: Writer - Storyteller
  social:
  - title: twitter
    url: http://twitter.com/imagine_kat
  - title: facebook
    url: https://www.facebook.com/kat.heiden
  - title: linkedin
    url: https://www.linkedin.com/in/katheiden22/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/imagine_kat
  - title: facebook
    url: https://www.facebook.com/kat.heiden
  - title: linkedin
    url: https://www.linkedin.com/in/katheiden22/
# Postal address (add as many lines as necessary)
address:
  - line: 10890 Vrain St.
  - line: Westminster, CO 80031

# Build settings
markdown: kramdown
permalink: pretty